services:
  db:
    image: postgres:latest
    container_name: kiosk_postgres_dev
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=uday
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kiosk
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
